# Generated by Django 6.0.1 on 2026-02-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
    ]
